name: Github Pages Deployment

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          source-directory: Frontend
          access-token: ${{ secrets.ACCESS_TOKEN }}
          build-command: npm run build
