name: Execute frontend tests and build for deployment
'on':
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Build
        run: |
            cd Frontend
            npm config set legacy-peer-deps true
            npm ci
            npm install -g @angular/cli
            ng build
      - name: Run Frontend unit tests
        run: |
          cd Frontend
          npm config set legacy-peer-deps true
          npm ci
          npm install -g @angular/cli
          ng test --browsers=ChromeHeadless --watch=false
